### ISSUE TITLE
debug Travis

### ISSUE THREAD

**Issue by Inne-Lemstra** [MWJMerkx/pcfb_project#2]
@richelbilderbeek
I have written a python3 script that works on my computer but not on travis.
What is a good way to debug travis, I want to know what travis has loaded in my variables and such.
Also I want to test how bash command (run via python) behave.
Should I add a lot of print statements to my script or is there a directer way, via interactive terminal etc.

description error:
Indexerror when cleaning up string I get from a lscpu call to bash.
I think that travis can't run this command for some reason and returns an empty list.

**Comment by richelbilderbeek** [comment]
> Should I add a lot of print statements to my script?
I am sorry, but yes, as there is no interactive debugger.

The error sounds as if some packages are absent: this is usually the case when I observe the same. Don't forget: `SELECT isn't  broken`.

**Comment by richelbilderbeek** [comment]
Oh, Travis CI does have an older Linux distro, add 

```
dist: trusty
```

to the top of your `.travis.yml` to use the newer distro Trusty Tahr. Perhaps that helps. :+1:

**Comment by MWJMerkx** [comment]
It's kinda odd, it gives and error that .run apparently doesnt exist for line 12 while on line 11 it does seem to accept it.

`File "./client/hardware_inquire.py", line 12, in <module>

    infoCPU = subprocess.run(comGetCPU, stdout= pipe)

AttributeError: 'module' object has no attribute 'run'`

**Comment by richelbilderbeek** [comment]
For me, it also fails when running locally:

```
p230198@pc-157-103:~$ git clone https://github.com/MWJMerkx/pcfb_project.git
Cloning into 'pcfb_project'...
remote: Counting objects: 139, done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 139 (delta 54), reused 138 (delta 53), pack-reused 0
Receiving objects: 100% (139/139), 1.67 MiB | 1.81 MiB/s, done.
Resolving deltas: 100% (54/54), done.
Checking connectivity... done.
p230198@pc-157-103:~$ cd pcfb_project/
p230198@pc-157-103:~/pcfb_project$ ./client/hardware_inquire.py
Traceback (most recent call last):
  File "./client/hardware_inquire.py", line 12, in <module>
    infoCPU = subprocess.run(comGetCPU, stdout= pipe)
AttributeError: 'module' object has no attribute 'run'
p230198@pc-157-103:~/pcfb_project$ 
```

Perhaps you forgot to `chmod +x ` the Python script? If yes, also modify the script in a trivial way (e.g. adding whitespace) before pushing to GitHub. git does not detect a `chmod`.

**Comment by MWJMerkx** [comment]
Seems that apparently theres a problem with there being some differences between python 3.4 and 3.5. Trying to fix those, then we'll try again.

**Comment by richelbilderbeek** [comment]
So the `chmod +x` wasn't it, neither the spelling errors. Thanks for helping me collaborate :-)

**Comment by MWJMerkx** [comment]
Thank you for the help, will let you know if we get it to work.

**Comment by richelbilderbeek** [comment]
Indeed, only the `3.5` build has a Python error message. Sound like you should only stick to that one and fix the Python script :+1:

**Comment by Inne-Lemstra** [comment]
Found the problem. The script calls lscpu which does not generate the same output for every linux distro.

In mint 18 it has a field Model name, the script searches for this. In other distros this field does not exist therefore will result in an empty list, leading to an indexerror.
