### ISSUE TITLE
I ran a test for you

### ISSUE THREAD

**Issue by Aoife10** [MWJMerkx/pcfb_project#5]
[aoife_Bwa_result.tar.gz](https://github.com/MWJMerkx/pcfb_project/files/733241/aoife_Bwa_result.tar.gz)
[Aoife_bowtie2_result.tar.gz](https://github.com/MWJMerkx/pcfb_project/files/733243/Aoife_bowtie2_result.tar.gz)

**Comment by MWJMerkx** [comment]
Sweet, 
Thanks :)
